POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de fasfy"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/3c22268f-def2-4a18-a870-bd12985aa935

###

POST http://localhost:3333/courses/1
Content-Type: application/json

{
  "title": "Alterei o nome do curso"
}

###

DELETE http://localhost:3333/courses/1