POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de fasfy 1",
  "description": "qualquer coisa"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/96e669ab-0324-4a39-88fe-99b9f099ff77
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYTRhMWFkMy0xYzk3LTQ3MTAtYjc2Mi0wMDNjMDdkYzg5YjUiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NTM2Mzk1MH0.pAOGlw85vwZbj6PKm-mX-G4M4ejvoFAEJNuNg4UBDlM

###

PUT http://localhost:3333/courses/1
Content-Type: application/json

{
  "title": "Alterei o nome do curso"
}

###

DELETE http://localhost:3333/courses/1

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "DaviLucca24@bol.com.br",
  "password": "123456"
}